### ISSUE TITLE
 I understand that, but when I test on 160*160 image with one face, the speed is so slow as 300ms/pic, I just want to know your real speed to find out if I missed anything.

### ISSUE THREAD

**Issue by Edwardmark** [Goingqs/PyramidBox#11]
why the model is such slow?

**Comment by Edwardmark** [comment]
I understand that, but when I test on 160*160 image with one face, the speed is so slow as 300ms/pic, I just want to know your real speed to find out if I missed anything. 
det0 time cost:0.02503800392150879
shrink:1
det1 time cost:0.025511980056762695
shrink:0.5
shrink:0.75
shrink:2
shrink:1.5
shrink:3
det2,3 time cost:0.17483925819396973
shrink:0.25
shrink:1.25
shrink:1.75
shrink:2.25
det4 time cost:0.12813091278076172
det cost all:0.35352015495300293
detected 1 faces  
It seems that your high accuracy is based on multi-scale ensemble, is that true?

**Comment by Edwardmark** [comment]
@Goingqs Please comment, thanks.

**Comment by hdjsjyl** [comment]
@Edwardmark  I meet the same problem. If I use model from this author, the testing speed is faster than model trained by this training code.

**Comment by Edwardmark** [comment]
@hdjsjyl  What is your speed? The test code the author provided, use multiple scale test to improve the accuracy, but that is quite slow, nealy 300ms/pic for 160x160 picture.

**Comment by Goingqs** [comment]
About 13FPS for 640*640 picture on GTX 1080Ti.

**Comment by Edwardmark** [comment]
@Goingqs This speed is only for single forward, such like 👍https://github.com/Goingqs/PyramidBox/blob/master/test.py#L236, but not https://github.com/Goingqs/PyramidBox/blob/master/test.py#L240, is that right? Thanks.

**Comment by Goingqs** [comment]
That's it

**Comment by Edwardmark** [comment]
@Goingqs Thank you very much.

**Comment by laycoding** [comment]
@Goingqs I test the model on V100 machine, but got about 200ms/pic, single scale, and the test time is not stable, floating in 100ms to 700ms,  any suggestion?
ThX!
