### ISSUE TITLE
what's the cuda and cudnn version you use?

### ISSUE THREAD

**Issue by hdjsjyl** [Goingqs/PyramidBox#12]
what's the cuda and cudnn version you use?

**Comment by Goingqs** [comment]
CUDA8.0 CUDNN5.1

**Comment by hdjsjyl** [comment]
@Goingqs   With cuda9.1 and cudnn7.0, when I use learning rate of 0.1, the loss is inf

**Comment by hdjsjyl** [comment]
@Goingqs   With cuda9.1 and cudnn7.0, when I use learning rate of 0.1, the loss is inf

**Comment by Goingqs** [comment]
Your lr is too large, 10^-3 is enough.

**Comment by hdjsjyl** [comment]
@Goingqs  , I am wrong. When I use lr with 0.001, loss is inf.

**Comment by hdjsjyl** [comment]
@Goingqs  , I am wrong. When I use lr with 0.001, loss is inf.

**Comment by Goingqs** [comment]
emmm, Can you show me your log of loss

**Comment by hdjsjyl** [comment]
@Goingqs , yes, I can upload it later. And for your model, you use the parameter "batch size 32, iterations 120000" or "batch size 16, iterations 120000"? I found that the weight_decay is 0.0001 in your code, but original paper is 0.0005, which is correct for your code? Thanks

**Comment by hdjsjyl** [comment]
@Goingqs  How many GPUs , what is the gpu, what is the batch size, and how long you need to train the model? These information is important for me, thank you very much.

**Comment by Goingqs** [comment]
2 GPUs, batch size is 16, iteration is 120000. The time cost for train depends on your GPU. I finish it in two days.

**Comment by hdjsjyl** [comment]
@Goingqs  what is the weight decay you use, original paper shows 0.0005, your code shows 0.0001, which is correct? Thanks

**Comment by Goingqs** [comment]
@hdjsjyl, my weight decay is 10^-4

**Comment by hdjsjyl** [comment]
@Goingqs   Thanks for your reply, I think your code is very good. Thanks

**Comment by hdjsjyl** [comment]
@Goingqs   Thanks for your reply, I think your code is very good. Thanks

**Comment by hdjsjyl** [comment]
@Goingqs   The following is the log, when I use learning rate is 0.001:

/home/lshi22/.local/lib/python3.5/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Initializing weights...
Loading Dataset...
Training SSD on WiderFace
/home/lshi22/.local/lib/python3.5/site-packages/torch/autograd/_functions/tensor.py:447: UserWarning: mask is not broadcastable to self, but they have the same number of elements.  Falling back to deprecated pointwise behavior.
  return tensor.masked_fill_(mask, value)
front and back Timer: 22.854674100875854 sec.
iter 0 || Loss: 71.4618 ||
Loss conf: 38.856040954589844 Loss loc: 13.214371681213379
Loss head conf: 28.07379722595215 Loss head loc: 10.708907127380371
lr: 0.001
Saving state, iter: 0
Traceback (most recent call last):
  File "train.py", line 241, in <module>
    train()
  File "train.py", line 188, in train
    loss_l, loss_c = criterion(tuple(out[0:3]), targets)
  File "/home/lshi22/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lshi22/PyramidBox/layers/modules/multibox_loss.py", line 102, in forward
    loss_c = log_sum_exp(batch_conf) - batch_conf.gather(1, conf_t.view(-1, 1))
  File "/home/lshi22/PyramidBox/layers/box_utils.py", line 246, in log_sum_exp
    return torch.log(torch.sum(torch.exp(x-x_max), 1, keepdim=True)) + x_max
RuntimeError: value cannot be converted to type float without overflow: inf

**Comment by Edwardmark** [comment]
@hdjsjyl I met the similar error as yours, how you solved it? Please help me out.

**Comment by Edwardmark** [comment]
@hdjsjyl @Goingqs I met the similar inf bug as follows:  
root@41a655357ffb:/app# python3 train.py 
Initializing weights...
Loading Dataset...
Training SSD on WiderFace
/usr/local/lib/python3.5/dist-packages/torch/autograd/_functions/tensor.py:447: UserWarning: mask is not broadcastable to self, but they have the same number of elements.  Falling back to deprecated pointwise behavior.
  return tensor.masked_fill_(mask, value)
front and back Timer: 10.605130195617676 sec.
iter 0 || Loss: 72.3941 ||
Loss conf: 28.603429794311523 Loss loc: 13.25808334350586
Loss head conf: 52.113525390625 Loss head loc: 8.951560020446777
lr: 0.001
Saving state, iter: 0
Traceback (most recent call last):
  File "train.py", line 241, in <module>
    train()
  File "train.py", line 188, in train
    loss_l, loss_c = criterion(tuple(out[0:3]), targets)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/app/layers/modules/multibox_loss.py", line 102, in forward
    loss_c = log_sum_exp(batch_conf) - batch_conf.gather(1, conf_t.view(-1, 1))
  File "/app/layers/box_utils.py", line 246, in log_sum_exp
    return torch.log(torch.sum(torch.exp(x-x_max), 1, keepdim=True)) + x_max
RuntimeError: value cannot be converted to type float without overflow: inf

Any clues to solve that? @Goingqs Thanks for your reply, I think your code is very elegant. Thanks
