### ISSUE TITLE
Confused about prior_box.py

### ISSUE THREAD

**Issue by Edwardmark** [Goingqs/PyramidBox#16]
what does the following line mean?
Why multiply scale by (2**(1/3))?
https://github.com/Goingqs/PyramidBox/blob/master/layers/functions/prior_box.py#L32

**Comment by Goingqs** [comment]
It just doesn't matter. If you wanna multi-scale anchor box, this may help.

**Comment by Edwardmark** [comment]
@Goingqs Thank you very much.
