### ISSUE TITLE
Can you give a Dockerfile that can run your code perfectly?

### ISSUE THREAD

**Issue by Edwardmark** [Goingqs/PyramidBox#19]
I use pytorch 0.3.1, but met lots of weired bug.  like:
cuda Runtime Error (77): an illegal memory access was encountered 
OverflowError: cannot convert float infinity to integer 
RuntimeError: value cannot be converted to type float without overflow: inf

**Comment by Edwardmark** [comment]
@Goingqs Maybe it is caused by the wider.lst error, can you give out a train list?  
I met the following error, maybe caused by list format?  
  File "train.py", line 240, in <module>
    train()
  File "train.py", line 175, in train
    images, targets = next(batch_iterator)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 267, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 55, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/app/data/widerface.py", line 99, in __getitem__
    im, gt, h, w = self.pull_item(index)
  File "/app/data/widerface.py", line 119, in pull_item
    img, boxes, labels = self.transform(img, target[:, :4], target[:, 4])
IndexError: too many indices for array  
Would you please give me some clue?

**Comment by Edwardmark** [comment]
@Goingqs This bug occurs now and then, do not know why. Could you help me out?

**Comment by Goingqs** [comment]
Maybe you should checkout your data. I guess your data in a wrong format....

**Comment by Edwardmark** [comment]
@Goingqs I gen the list using the following format:
img_path num_faces x1 y1 w1 h1 x2 y2 w2 h2 ...
And I use the official wider_face dataset, and I also used cv2.imread to check all the imgs, did you do some special tricks to organize the training data or sth that not mentioned in readme? Or could you just give out a training list please? That can make the re-implementation more easily. Thank you very much, your code impressed me.

**Comment by Edwardmark** [comment]
@Goingqs Can you explain the data format you used? Or just could you please show the list you used or docker image? Thanks very much.

**Comment by Edwardmark** [comment]
@Goingqs I delete the imgs with height 0 and add a small epsilon in the log loss, and it is solved, thanks guy, your code is really beautiful.

**Comment by seefun** [comment]
@Edwardmark  how did you change the code? I meet the same problem and i believe the data and annos are right.

**Comment by ywcmaike** [comment]
@Edwardmark @Goingqs   I also encountered the problem.  Can you give me the anno list, and the change of the code.    thanks!
my email is 2755289083@qq.com
