### ISSUE TITLE
A inf bug, please help me out.

### ISSUE THREAD

**Issue by Edwardmark** [Goingqs/PyramidBox#20]
root@41a655357ffb:/app# python3 train.py 
Initializing weights...
Loading Dataset...
Training SSD on WiderFace
/usr/local/lib/python3.5/dist-packages/torch/autograd/_functions/tensor.py:447: UserWarning: mask is not broadcastable to self, but they have the same number of elements.  Falling back to deprecated pointwise behavior.
  return tensor.masked_fill_(mask, value)
front and back Timer: 10.275606155395508 sec.
iter 0 || Loss: 90.8623 ||
Loss conf: 51.309993743896484 Loss loc: 11.424317359924316
Loss head conf: 48.754676818847656 Loss head loc: 7.501279354095459
lr: 0.0001
Saving state, iter: 0
front and back Timer: 0.7664861679077148 sec.
iter 10 || Loss: 62.3223 ||
Loss conf: 12.217093467712402 Loss loc: 17.27483367919922
Loss head conf: 43.204200744628906 Loss head loc: 22.456457138061523
lr: 0.0001
front and back Timer: 0.7011480331420898 sec.
iter 20 || Loss: 25.3138 ||
Loss conf: 13.556425094604492 Loss loc: 6.718225955963135
Loss head conf: 4.488845348358154 Loss head loc: 5.589457988739014
lr: 0.0001
front and back Timer: 0.7081215381622314 sec.
iter 30 || Loss: 16.7039 ||
Loss conf: 4.1354851722717285 Loss loc: 6.339954853057861
Loss head conf: 6.332630157470703 Loss head loc: 6.124255180358887
lr: 0.0001
front and back Timer: 0.7141270637512207 sec.
iter 40 || Loss: 12.9531 ||
Loss conf: 2.785682201385498 Loss loc: 5.851232528686523
Loss head conf: 3.0570006370544434 Loss head loc: 5.575360298156738
lr: 0.0001
front and back Timer: 0.7503578662872314 sec.
iter 50 || Loss: 23.3493 ||
Loss conf: 13.566965103149414 Loss loc: 5.035085678100586
Loss head conf: 4.751973628997803 Loss head loc: 4.742441654205322
lr: 0.0001
/app/utils/augmentations.py:266: RuntimeWarning: divide by zero encountered in double_scalars
  ratio = float(target_anchor) / rand_Side
front and back Timer: 0.7871015071868896 sec.
iter 60 || Loss: 12.1471 ||
Loss conf: 3.0819289684295654 Loss loc: 5.024109363555908
Loss head conf: 3.064208507537842 Loss head loc: 5.017943382263184
lr: 0.0001
Traceback (most recent call last):
  File "train.py", line 241, in <module>
    train()
  File "train.py", line 175, in train
    images, targets = next(batch_iterator)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
OverflowError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 55, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/app/data/widerface.py", line 99, in __getitem__
    im, gt, h, w = self.pull_item(index)
  File "/app/data/widerface.py", line 119, in pull_item
    img, boxes, labels = self.transform(img, target[:, :4], target[:, 4])
  File "/app/utils/augmentations.py", line 509, in __call__
    return self.augment(img, boxes, labels)
  File "/app/utils/augmentations.py", line 53, in __call__
    img, boxes, labels = t(img, boxes, labels)
  File "/app/utils/augmentations.py", line 269, in __call__
    if int(height * ratio * width * ratio) > self.maxSize*self.maxSize:
OverflowError: cannot convert float infinity to integer

**Comment by hdjsjyl** [comment]
I meet the same error. Let's look forward to the answers of the author of the code.

**Comment by Edwardmark** [comment]
@hdjsjyl Yes，Thanks. I add a small numble eps like 1e-10 in the log or divide operator in the loss calculation, maybe helpful.

**Comment by hdjsjyl** [comment]
@Edwardmark  First, the author said he can train the model with spending two days. But I can't do that. After you change the parameters, you can train the model with spending two days and get the similar performance, I think that will be perfect. If you can get that, pls share parameters setting, thanks

**Comment by Edwardmark** [comment]
@hdjsjyl Now, I cannot train it. I'll try. Thanks.

**Comment by Edwardmark** [comment]
@Goingqs Please comment, thanks. The bug can be reproduced by just git clone the repo, and run train.py.

**Comment by Edwardmark** [comment]
@hdjsjyl I did some changes as follows:
1. changed the lr = 1e-5, 
2. using two GPU with batch_size = 16, comment cudnn.benchnark=True in train.py
3. change line 275 in augmentations.py to the following line to avoid zero resizing bug:
if min(ratio * image.shape[0], ratio * image.shape[1]) > 1.0:
    image = cv2.resize(image, None, None, fx=ratio, fy=ratio, interpolation=interp_method)
4.change line 123 in augmentations.py to the following code to avoid bug in data preprocessing:
```
if image.shape[0] == 0 or image.shape[1] == 0:  
    image = np.zeros((self.size,self.size,3), np.float64)  
else:
    image = cv2.resize(image, (self.size,self.size),interpolation=interp_method)
```
5. change line 105 in augmentations.py as follows to avoid divided by zero error:
```
class ToPercentCoords(object):
    def __call__(self, image, boxes=None, labels=None):
        height, width, channels = image.shape 
        #print(image.shape)
        if width == 0:
            boxes[:, 0] *= 1
            boxes[:, 2] *= 1
            labels = np.zeros(len(boxes), np.float64)
        else:
            boxes[:, 0] /= width
            boxes[:, 2] /= width
        if height == 0:
            boxes[:, 1] *= 1
            boxes[:, 3] *= 1
            labels = np.zeros(len(boxes), np.float64)
        else:
            boxes[:, 1] /= height
            boxes[:, 3] /= height

        return image, boxes, labels
```
6. Add a small epsilon in box_utils.py Line 246 like:
return torch.log(torch.sum(torch.exp(x-x_max), 1, keepdim=True) + 1e-8) + x_max
Then the inf bug is gone, and the loss seems to converge fine , and I can use batch-size = 16 now.

But I am still so confused why @Goingqs you can use batch_size as 32, because I also have 2 x 1080, but I can only set batch_size = 16, and why you can use 1e-3 without inf bug, is that because  you  used iter_size in your own code different from the code provided here? Please comment @hdjsjyl @Goingqs , thanks.   

The output log for the first 100 iter is as follows:
```
root@498726be2ac3:/app# python3 train.py 
Initializing weights...
Loading Dataset...
epoch_size is 804
Training SSD on WiderFace
/usr/local/lib/python3.5/dist-packages/torch/autograd/_functions/tensor.py:447: UserWarning: mask is not broadcastable to self, but they have the same number of elements.  Falling back to deprecated pointwise behavior.
  return tensor.masked_fill_(mask, value)
[0], Mon Sep 10 09:22:43 2018, Phase: Train
lr: 1e-05, Loss: 71.97879028320312, Loss conf: 48.94547653198242, Loss loc: 12.84052848815918, Loss head conf: 12.176727294921875, Loss head loc: 8.208847999572754
Saving state, iter: 0
[10], Mon Sep 10 09:22:57 2018, Phase: Train
lr: 1e-05, Loss: 40.980892181396484, Loss conf: 22.25665283203125, Loss loc: 11.2422513961792, Loss head conf: 6.108275890350342, Loss head loc: 8.855697631835938
[20], Mon Sep 10 09:23:11 2018, Phase: Train
lr: 1e-05, Loss: 27.442638397216797, Loss conf: 8.968762397766113, Loss loc: 10.66262435913086, Loss head conf: 7.677834510803223, Loss head loc: 7.944672107696533
[30], Mon Sep 10 09:23:25 2018, Phase: Train
lr: 1e-05, Loss: 17.292198181152344, Loss conf: 4.245013236999512, Loss loc: 7.235851287841797, Loss head conf: 4.947673320770264, Loss head loc: 6.674994468688965
[40], Mon Sep 10 09:23:39 2018, Phase: Train
lr: 1e-05, Loss: 13.995523452758789, Loss conf: 3.5844204425811768, Loss loc: 5.882469654083252, Loss head conf: 3.347559928894043, Loss head loc: 5.709707260131836
[50], Mon Sep 10 09:23:53 2018, Phase: Train
lr: 1e-05, Loss: 18.450191497802734, Loss conf: 4.2826619148254395, Loss loc: 7.51425838470459, Loss head conf: 5.73707389831543, Loss head loc: 7.5694661140441895
[60], Mon Sep 10 09:24:07 2018, Phase: Train
lr: 1e-05, Loss: 18.0396671295166, Loss conf: 2.807037830352783, Loss loc: 8.367473602294922, Loss head conf: 6.011973857879639, Loss head loc: 7.7183403968811035
[70], Mon Sep 10 09:24:21 2018, Phase: Train
lr: 1e-05, Loss: 17.00033187866211, Loss conf: 3.4282426834106445, Loss loc: 8.216795921325684, Loss head conf: 4.287439346313477, Loss head loc: 6.423144340515137
[80], Mon Sep 10 09:24:35 2018, Phase: Train
lr: 1e-05, Loss: 15.531353950500488, Loss conf: 3.3619985580444336, Loss loc: 6.904052734375, Loss head conf: 4.412776947021484, Loss head loc: 6.117828845977783
[90], Mon Sep 10 09:24:49 2018, Phase: Train
lr: 1e-05, Loss: 16.022964477539062, Loss conf: 3.863846778869629, Loss loc: 7.233030796051025, Loss head conf: 3.789954900741577, Loss head loc: 6.062218189239502
[100], Mon Sep 10 09:25:03 2018, Phase: Train
lr: 1e-05, Loss: 14.601643562316895, Loss conf: 4.023736000061035, Loss loc: 5.717489242553711, Loss head conf: 3.9815118312835693, Loss head loc: 5.739323616027832
```
When the iteration is 29690, the loss is as follows:
[29690] Tue Sep 11 01:44:21 2018, lr: 1e-05, Loss: 7.786163330078125, Loss conf: 2.13901948928833, Loss loc: 2.9982781410217285, Loss head conf: 2.0863053798675537, Loss head loc: 3.21142578125 
But the res in Widerface val is 0.00 for all sets...
@Goingqs What is the loss when converged? Can you give us a reference? Can you provide a code that can be run successfully? Thanks.

**Comment by hdjsjyl** [comment]
@Edwardmark  I meet the same question as yours. @Goingqs  Can you publish the code that you use to train the model you publish? Whatever, it has some comments or not clear, it does not matter. I just want to make it run successfully. Thanks

**Comment by Edwardmark** [comment]
@hdjsjyl Any progress now? What is your loss, can the model converge?

**Comment by hdjsjyl** [comment]
@Edwardmark  No. I am trying to find problem of the code.

**Comment by hdjsjyl** [comment]
@Edwardmark  I used lr = 0.0001, I get the results for hard set 0.75. I do not know the reason.

**Comment by Edwardmark** [comment]
@hdjsjyl Have you change any code? Can you give me you list?

**Comment by hdjsjyl** [comment]
@Edwardmark    I donot change anything.  How about your results?

**Comment by Edwardmark** [comment]
@hdjsjyl [29690] Tue Sep 11 01:44:21 2018, lr: 1e-05, Loss: 7.786163330078125, Loss conf: 2.13901948928833, Loss loc: 2.9982781410217285, Loss head conf: 2.0863053798675537, Loss head loc: 3.21142578125
 That is my result, quite bad. I don't know why. Can you email me your train lst? I delete the four imgs with 0 height or width, but it did not work.

**Comment by hdjsjyl** [comment]
@Edwardmark    What is your result on the validation set of wider face? Tell me the email. I will send it to you.

**Comment by Edwardmark** [comment]
@hdjsjyl My email is : JordanDong@yeah.net.

**Comment by Edwardmark** [comment]
@hdjsjyl I have changed lots of code to make the train.py run, but the result is 0 on wider face, so I guess the list I generate is wrong or I missed something, so please send me your list, thank you very much.

**Comment by Edwardmark** [comment]
@hdjsjyl       email:       JordanDong@yeah.net

**Comment by Edwardmark** [comment]
@hdjsjyl Have you send to me? Looking forwad to your reply.

**Comment by hdjsjyl** [comment]
@Edwardmark   Check your email

**Comment by Edwardmark** [comment]
@hdjsjyl Thank you very much. Sorry to bother you. Thank you very much, looking forward to your reply.

**Comment by Edwardmark** [comment]
@hdjsjyl @Goingqs Finally, I knew that the bug is caused by not fine-tuning from resnet50, but training from scratch. When fine-tuning, the bug is fixed. Thanks, guys.

**Comment by Edwardmark** [comment]
But I still got inf error when run train.py.... The log is as follows:  
```
[1850] Mon Sep 17 09:48:51 2018, lr: 0.001, Loss: 2.7916696071624756, Loss conf: 0.14018911123275757, Loss loc: 1.6918648481369019, Loss head conf: 0.1206364631652832, Loss head loc: 1.7985951900482178
[1860] Mon Sep 17 09:49:09 2018, lr: 0.001, Loss: 6.701171875, Loss conf: 0.7105586528778076, Loss loc: 4.966256618499756, Loss head conf: 0.4187043607234955, Loss head loc: 1.6300097703933716
[1870] Mon Sep 17 09:49:26 2018, lr: 0.001, Loss: 12.630814552307129, Loss conf: 5.02933406829834, Loss loc: 5.956894397735596, Loss head conf: 0.23180310428142548, Loss head loc: 3.0573678016662598
[1880] Mon Sep 17 09:49:43 2018, lr: 0.001, Loss: 4.4732279777526855, Loss conf: 0.0017598399426788092, Loss loc: 3.191554069519043, Loss head conf: 0.04546787217259407, Loss head loc: 2.5143604278564453
[1890] Mon Sep 17 09:50:01 2018, lr: 0.001, Loss: 9.846983909606934, Loss conf: 5.4925713539123535, Loss loc: 3.1863880157470703, Loss head conf: 0.06839369982481003, Loss head loc: 2.267655849456787
[1900] Mon Sep 17 09:50:18 2018, lr: 0.001, Loss: 9.011049270629883, Loss conf: 2.5268781185150146, Loss loc: 4.4529032707214355, Loss head conf: 0.4651152193546295, Loss head loc: 3.597421646118164
[1910] Mon Sep 17 09:50:35 2018, lr: 0.001, Loss: 7.756189346313477, Loss conf: 0.40258291363716125, Loss loc: 4.886757850646973, Loss head conf: 0.7305191159248352, Loss head loc: 4.203177452087402
[1920] Mon Sep 17 09:50:52 2018, lr: 0.001, Loss: 27.20599937438965, Loss conf: 5.795321464538574, Loss loc: 17.7840633392334, Loss head conf: 2.320366859436035, Loss head loc: 4.93286657333374
[1930] Mon Sep 17 09:51:09 2018, lr: 0.001, Loss: 3.0901373240374994e+26, Loss conf: 1.0014003177202782e+26, Loss loc: 2.0887370063172212e+26, Loss head conf: 169573711872.0, Loss head loc: 133058076672.0
```
