### ISSUE TITLE
Did you use loss_head and loss_head_loc in your public model?

### ISSUE THREAD

**Issue by Edwardmark** [Goingqs/PyramidBox#23]
I noticed that you do not use body loss, so why keep head loss? I cannot find the way how you match the head anchor to gt like the paper, any clues? Or you just use LFPN, data aug, and max-out to train a typical face detector without caring about contextual information like the paper? Is the inf bug caused by the head loss? Would you kindly give me a hint? @Goingqs

**Comment by Goingqs** [comment]
The released model is trained without body loss. I think you should check your data. Make sure that your label is in a correct format. With lr=0.001 and batch-size=16 you can get a similar result

**Comment by Edwardmark** [comment]
@Goingqs Thanks, so can you give us a list with the correct format? I use the same format as your readme file described, but it did not work. Please help me, thank you very much.

**Comment by Edwardmark** [comment]
@Goingqs Thanks, please show your train list please, it is the key to re-implement your model.
