### ISSUE TITLE
Did you train your model from scratch or fine-tune using a resnet50 network weights?

### ISSUE THREAD

**Issue by Edwardmark** [Goingqs/PyramidBox#27]
@Goingqs Please comment.

**Comment by Goingqs** [comment]
Fine-tune from a pretrained model

**Comment by Edwardmark** [comment]
@Goingqs That is an important information, thank you very much.

**Comment by Edwardmark** [comment]
@Goingqs And that is the reason why we get inf error. Because we train from scratch.
