### ISSUE TITLE
WIDER FACE list

### ISSUE THREAD

**Issue by hdjsjyl** [Goingqs/PyramidBox#3]
Thanks for your code. It is very good. Can you share your wider face list? Because when I use my wider face list, some pictures show that height or width is equal to zero.

**Comment by Goingqs** [comment]
Just discard those faces. My list is the same as the original but in a different format.

**Comment by hdjsjyl** [comment]
@Goingqs  thanks

**Comment by YueXiNPU** [comment]
@hdjsjyl  @Goingqs Sorry, When running train.py, it release "No such file or directory: '/home/guoqiushan/share/face_box/wider.list'". What is format of the wider.list? how to generate? Thank you very much.
