### ISSUE TITLE
shape not match

### ISSUE THREAD

**Issue by seefun** [Goingqs/PyramidBox#34]
PyramidBox/layers/modules/multibox_loss.py", line 105, in forward
    loss_c[pos] = 0  # filter out pos boxes for now
RuntimeError: The shape of the mask [4, 34125] at index 0 does not match the shape of the indexed tensor [136500, 1] at index 0

I  set the batchsize to 4 and I use my own dataset. When i run train.py I occur this problem. why does it happen?

**Comment by xxlei** [comment]
hei, i meet the same problem, do you sloved it ?

**Comment by seefun** [comment]
> hei, i meet the same problem, do you sloved it ?

no idea...

**Comment by nuanyang123** [comment]
I also met the same problem. Has anyone solved it?

**Comment by abcdvzz** [comment]
> hei, i meet the same problem, do you sloved it ?

Did u solve the problem?

**Comment by abcdvzz** [comment]
> PyramidBox/layers/modules/multibox_loss.py", line 105, in forward
> loss_c[pos] = 0 # filter out pos boxes for now
> RuntimeError: The shape of the mask [4, 34125] at index 0 does not match the shape of the indexed tensor [136500, 1] at index 0
> 
> I set the batchsize to 4 and I use my own dataset. When i run train.py I occur this problem. why does it happen?

Did u solve the problem?

**Comment by Tianlock** [comment]
@seefun hello, have you solved the problem? i met the same problem.

**Comment by Tianlock** [comment]
@xxlei  Hi, have you solved it, i met the same problem, thanks

**Comment by seefun** [comment]
@abcdvzz @Tianlock I give up using this codes. And I try to use the official pyramidbox codes which you can find in [PaddlePaddle/models](https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/face_detection)

**Comment by NarcissusInMirror** [comment]
I think this repo is modified on the [pytorch version of SSD](https://github.com/amdegroot/ssd.pytorch), the original repo has the related issue.  All you need is to change few lines of code in `multibox_loss.py` and `train.py` as described in 
[this](https://github.com/amdegroot/ssd.pytorch/issues/173#issuecomment-438516944) and [this](https://github.com/amdegroot/ssd.pytorch/issues/173#issuecomment-475612639) issue. It works well for me.
