### ISSUE TITLE
train error with CPU

### ISSUE THREAD

**Issue by pbdahzou** [Goingqs/PyramidBox#4]
Great work! 
I use your code to train with CPU and failed, the error is as following:
(my setting: python 2.7, opencv 3, pytorch 0.4)

  File "xxx/PyramidBox/layers/box_utils.py", line 179, in matchNoBipartite
    best_truth_overlap = best_truth_overlap.cuda()
RuntimeError: torch.cuda.FloatTensor is not enabled.

**Comment by Goingqs** [comment]
Sorry, hard code. You can delete it if you train with CPU
