### ISSUE TITLE
Cannot use the model

### ISSUE THREAD

**Issue by hjzzju** [Goingqs/PyramidBox#41]
Thanks for your codes
But it seems that the model downloaded works bad with pytorch 0.4.1 - cpu
"Error(s) in loading state_dict for PyramidBox:   Unexpected key(s) in state_dict: "conv1.weight", "bn1.weight", "bn1.bias", "bn1.running_mean", "bn1.running_var", "layer1.0.conv1.weight", "layer1.0.bn1.weight..."
I don't know how to fix it
Hope you can give some advice

**Comment by Goingqs** [comment]
You can save your model and check the keys name. I guess your model have a prefix of module
