### ISSUE TITLE
shape error

### ISSUE THREAD

**Issue by Tianlock** [Goingqs/PyramidBox#43]
RuntimeError: The shape of the mask [4, 34125] at index 0 does not match the shape of the indexed tensor [136500, 1] at index 0

hello, i met this error during training, can you help me? thanks.

**Comment by Goingqs** [comment]
Hi, can you provide more information?  Your version of Pytorch, which line reports the runtime error?

**Comment by eiffelmen** [comment]
Hi,how do you deal with it?
