### ISSUE TITLE
about priors/anchors

### ISSUE THREAD

**Issue by foralliance** [Goingqs/PyramidBox#46]
@Goingqs  HI
code中，**设置了2组priors，一组针对face，一组针对head**．
**face_priors**：6个预测分支对应6组，尺度分别为16，32，64，128，256，512．
**head_priors**：5个预测分支对应5组，尺度分别为16，32，64，128，256．
比如说：
对于**face_priors**，第1个分支的第1个anchor，对应回原图（640的尺寸），坐标为（2，2，16，16）
对于**head_priors**，第2个分支的第1个anchor，对应回原图（640的尺寸），坐标为（4，4，16，16）

**您这样设计的目的是什么呢？？**
自己的理解：比如在第1个特征分支上，对于face_anchor，第1个anchor坐标为（2，2，16，16），那么为了体现这个**face_anchor**对应的**head_anchor**，在第2个特征分支上坐标应该为（2，2，32，32）吧．为什么是（4，4，16，16）呢？？
或者说自己本身这样的理解就有问题．

麻烦了！！

**Comment by Goingqs** [comment]
你好, 设计是根据文章来的. 这里没有使用扩大的anchor,是因为anchor和gt box同时扩大是等价的

**Comment by foralliance** [comment]
谢谢你的回答．
我能不能这么理解：
这是一个同步过程，要么gt和anchor都扩大，要么gt和anchor都不动
比如：正常来说，head_anchor需要扩大，对应的根据paper，对应的head_gt也要扩大（这点paper明确说明，而且给出了扩大方法）．
而你在code中，并没有会head_gt进行扩大，那么对应的head_anchor也就没有进行相应的扩大．
这样的理解对吗？？


还有1点：
第1个head_anchor是（4，4，16，16）
第1个face_anchor是（2，2，16，16）
自认为2者的中心点应该保持一直吧．你code中却发生了变化．为什么这么做呢？

**Comment by Goingqs** [comment]
发生了微小的偏移对结果影响不大,关于对gt 和 anchor 的理解是正确的.

**Comment by foralliance** [comment]
@Goingqs 
谢谢！！
