### ISSUE TITLE
@Goingqs I test the model on V100 machine, but got about 200ms/pic, single scale, and the test time is not stable, floating in 100ms to 700ms,  any suggestion?

### ISSUE THREAD

**Issue by laycoding** [Goingqs/PyramidBox#47]
@Goingqs I test the model on V100 machine, but got about 200ms/pic, single scale, and the test time is not stable, floating in 100ms to 700ms,  any suggestion?
ThX!

_Originally posted by @laycoding in https://github.com/Goingqs/PyramidBox/issues/11#issuecomment-451348799_

**Comment by Goingqs** [comment]
Can you provide more details? What is your batch size? How many pics did you test?

**Comment by laycoding** [comment]
Thank you for reply~
![image](https://user-images.githubusercontent.com/17764091/50874482-10259f00-13ff-11e9-8d03-d685ca7c05ce.png)
first, i download the model you provide, and do small change on test.py to single_scale_test.py shrink=1. then, test all of the 3226 pics in VAL SET with batch_size=1, got the result above this.

**Comment by laycoding** [comment]
by the way, i need do "torch.cuda.empty_cache()" after every batch to avoid GPU memory overflow. Do you konw any reason might cause that? It might slow down the speed a bit(still slow before this), but if i don't do that, it will jumps out "CUDA out of memory" after about 3000 iters on V100 16G machine

**Comment by Tianlock** [comment]
@Goingqs i also met the error when i inference images in test.py. And the test code occupy nealy 16G memory an gpu. As we know, usually test doesn't need too much memory. Do you know the reason? Thank you again
