### ISSUE TITLE
what gamma should be in learning rate decay

### ISSUE THREAD

**Issue by luojiapeng14** [Goingqs/PyramidBox#49]
While I train the model, it report in 8e4 steps
Traceback (most recent call last):
  File "train.py", line 241, in <module>
    train()
  File "train.py", line 160, in train
    adjust_learning_rate(optimizer, args.gamma, step_index)
AttributeError: 'Namespace' object has no attribute 'gamma'
I checked the code and found the train.py lacked the gamma paramters.
Could you tell us how large the gamma should be here？
I really appreciate it if you can give use some advice

**Comment by Goingqs** [comment]
We usually set gamma to 0.1

**Comment by luojiapeng14** [comment]
Thank you for replying.
