### ISSUE TITLE
Can you public your training information, graphics card, memory, and how much time to train it?

### ISSUE THREAD

**Issue by hdjsjyl** [Goingqs/PyramidBox#5]
Thanks for your code again. What graphics card is used to train PyramidBox and how much memory, how long time you need to train the network? Thank you.

**Comment by Goingqs** [comment]
GTX 1080TI, the memory is depend on your batch size.

**Comment by hdjsjyl** [comment]
I check code and find that batch_size is equal to 32, iterations is 120000, image size is 640*640; but the paper says that batch_size is equal to 16, iterations is 120000, image size is 600*600. So I want to ask which setting you have used. Thanks.

**Comment by Edwardmark** [comment]
@hdjsjyl @Goingqs Using batchsize 32, I got the following error when run train.py, I use two 1080TI and 32G memory, can you help me out please?  
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58  

I understand that it is a gpu memory issue, but I use the same setting as yours, why can't I train with batch 32? I change batch size to 16, and now it works.
