### ISSUE TITLE
For wider face val set results, mAP of hard set is 1.766, mAP of medium set is 2.557, mAP of easy set is 1.704?

### ISSUE THREAD

**Issue by hdjsjyl** [Goingqs/PyramidBox#6]
Why mAP is greater than 1, I do not get the same results as what paper has shown.

**Comment by Goingqs** [comment]
Wow, you'd better check you eval tool.

**Comment by hdjsjyl** [comment]
@Goingqs  For your model, the mAP of hard set of validation set is 49.1 not 89.0. Do  you think what is the reason? Thanks.
