### ISSUE TITLE
what the speed is your model?

### ISSUE THREAD

**Issue by Edwardmark** [Goingqs/PyramidBox#9]
I tried some samples, and found that it is too slow, what is your model speed? And can it run in batch?

**Comment by Goingqs** [comment]
The speed is depend on the image shape. If the images are in  the same shape, you can do it.

**Comment by Edwardmark** [comment]
@Goingqs I understand that, but when I test on 160*160 image with one face, the speed is so slow as 300ms/pic, I just want to know your real speed to find out if I missed anything.
